### ISSUE TITLE
JSONDecodError

### ISSUE THREAD

**Issue by danhiris** [SumoLogic/collector-management-client#24]
I'm getting the following error when trying to listversions.

Tried python 2.7 and 3.7, getting the same issue.

Traceback (most recent call last):
  File "sumo_mgmt.py", line 710, in <module>
    collectors = get_collectors('collectors', {'collectorType': 'Installable'})
  File "sumo_mgmt.py", line 240, in get_collectors
    log('[ERROR] %s' % r.json()['message'].lower()[:-1])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by danhiris** [comment]
I figured out the problem. The URL I had to use was https://api.us2.sumologic.com/api/v1/.

For details on which API url to use, check: https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security
